version: '3.8'

services:

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=db_ewen

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8090:8080"
    environment:
      - ADMINER_DEFAULT_SYSTEM=postgres
      - ADMINER_DEFAULT_SERVER=postgres
      - ADMINER_DEFAULT_USER=admin
      - ADMINER_DEFAULT_PASSWORD=root
      - ADMINER_DEFAULT_DATABASE=db_ewen

  flyway:
    image: flyway/flyway:latest
    depends_on:
      - postgres
    volumes:
      - ./migrations/:/flyway/sql/
    command: -url=jdbc:postgresql://postgres:5432/db_ewen?allowPublicKeyRetrieval=true -schemas=db_ewen -user=admin -password=root -connectRetries=60 migrate

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    container_name: zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000

  broker:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
      - "9093:9093"
    container_name: broker
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://broker:9092,PLAINTEXT_HOST://localhost:9093
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
